name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubunto-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multile script
        run: |
          node -v
          npm -v
